/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class kr_greedyeater_gadget_util_GlobalProxyJNI */

#ifndef _Included_kr_greedyeater_gadget_util_GlobalProxyJNI
#define _Included_kr_greedyeater_gadget_util_GlobalProxyJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     kr_greedyeater_gadget_util_GlobalProxyJNI
 * Method:    activateGlobalProxy
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_kr_greedyeater_gadget_util_GlobalProxyJNI_activateGlobalProxy
  (JNIEnv *, jclass, jstring);

/*
 * Class:     kr_greedyeater_gadget_util_GlobalProxyJNI
 * Method:    deactivateGlobalProxy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_kr_greedyeater_gadget_util_GlobalProxyJNI_deactivateGlobalProxy
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
