/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_a3sc_mimic_util_GlobalProxyJNI */

#ifndef _Included_com_a3sc_mimic_util_GlobalProxyJNI
#define _Included_com_a3sc_mimic_util_GlobalProxyJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_a3sc_mimic_util_GlobalProxyJNI
 * Method:    activateGlobalProxy
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_a3sc_mimic_util_GlobalProxyJNI_activateGlobalProxy
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_a3sc_mimic_util_GlobalProxyJNI
 * Method:    deactivateGlobalProxy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_a3sc_mimic_util_GlobalProxyJNI_deactivateGlobalProxy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
